igs/urls.py
from re import template
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from account.views import UserPasswordResetDoneView, UserPasswordResetView, UserPasswordResetConfirmView

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('account.urls')),
    path('upload/', include('upload.urls')),
    path('grading/', include('grading.urls')),
    path('result/', include('result.urls')),

    path('password_reset/', UserPasswordResetView.as_view(),
        name='password_reset'),

    path('password_reset/done/', UserPasswordResetDoneView.as_view(),
        name='password_reset_done'),

    path('reset/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(
        template_name='password_reset/password_reset_confirm.html'),
        name='password_reset_confirm'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='password_reset/password_reset_complete.html'),
        name='password_reset_complete'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pragmatic/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accountapp.urls')),
]

upload/urls.py
from django.urls import path
# from upload.views import PickPhotoView
from . import views
from django.views.generic import TemplateView

app_name = "upload"

urlpatterns = [
    path('pick_photo', TemplateView.as_view(template_name='upload/pick_photo.html'), name='pick_photo'),
    path('predict', views.predict, name='predict'),
    path('error_page', views.error_page, name="error_page")
]

upload/models.py
from django.db import models
from account.models import User

class Results(models.Model):
    register_date = models.DateField(auto_now_add=True)
    img_file_path = models.TextField(null=False)
    first_grade = models.CharField(max_length=4, null=False)
    first_grade_percentage = models.IntegerField(null=False)
    second_grade = models.CharField(max_length=4, null=False)
    second_grade_percentage = models.IntegerField(null=False)
    third_grade = models.CharField(max_length=4, null=False)
    third_grade_percentage = models.IntegerField(null=False)
    modified_grade = models.CharField(max_length=4, null=True, blank=True)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return str(self.pk)

    class Meta:
        ordering = ['-register_date']

upload/forms.py
from django import forms

class UploadForm(forms.Form):
    upimg = forms.ImageField()
    

upload/views.py
import re
from django.shortcuts import redirect, render
import os
import json
import numpy as np
from PIL import Image
from django.http import HttpResponse
from igs import settings
from . import forms
from .apps import UploadConfig
import tensorflow as tf
from upload.models import Results
from account.models import User

def predict(request):
    form = forms.UploadForm(request.POST, request.FILES)

    if form.is_valid(): 
        clean_data = form.cleaned_data 
        img_field  = clean_data['upimg']
        
        image = Image.open(img_field) 
        image_resize = image.resize((512,512)) 
        image_arr = np.array(image_resize) 
        image_arr = image_arr/255. 
        input_tensor = image_arr[np.newaxis, ...] 

        model = UploadConfig.model
        pred = model.predict(input_tensor) 
        
        if len(pred[0]) == 0: # 사진의 화질이 좋지 않아서 검출이 되지 않는 경우
            return redirect('/upload/error_page')

        # 후처리
        pred_boxes = pred[:,:, :4] # 예측한 bbox 좌표
        pred_conf = pred[:, :, 4:] # 예측한 class 별 확률
        
        tf.reshape(pred_boxes, (tf.shape(pred_boxes)[0], -1, 1, 4)).shape
        tf.reshape(pred_conf, (tf.shape(pred_conf)[0], -1, tf.shape(pred_conf)[-1])).shape

        # 추후 모델 개선 후 수정
        IOU_THRESH = 0.2
        CONFIDENCE_SORE_THRESH = 0.2

        boxes, scores , classes, valid_detections = tf.image.combined_non_max_suppression(
                boxes = tf.reshape(pred_boxes, (tf.shape(pred_boxes)[0], -1, 1, 4)), # bbox 좌표 추론값
                scores = tf.reshape(pred_conf, (tf.shape(pred_conf)[0], -1, tf.shape(pred_conf)[-1])),
                max_output_size_per_class = 50, 
                max_total_size = 3, 
                iou_threshold = IOU_THRESH, 
                score_threshold = CONFIDENCE_SORE_THRESH, 
        )

        # Result 모델에 들어갈 내용 찾기
        min_y = boxes[0][0][0]
        min_x = boxes[0][0][1]
        max_y = boxes[0][0][2]
        max_x = boxes[0][0][3]

        # box의 위치 찾기를 실패하는 경우 에러 페이지 연결
        flag = True

        for i in range(len(pred[0])):
            print(pred[0][i][0], pred[0][i][1], pred[0][i][2], pred[0][i][3])
            if pred[0][i][0] == min_y and pred[0][i][1] == min_x and pred[0][i][2] == max_y and pred[0][i][3]==max_x:
                class_prob = [pred[0][i][4], pred[0][i][5], pred[0][i][6], pred[0][i][7], pred[0][i][8]]
                flag = False
                break    
        
        if flag:
            return redirect('/upload/error_page')     
        
        sorted_index = np.argsort(class_prob)
        class_str = ["1++", "1+", "1", "2", "3"]
       
       # 만약 로그인이 되어 있다면 현재 로그인 된 사용자의 pk로 설정
       # 그렇지 않다면 비회원으로 등록

        if request.user.is_authenticated:
            user = User(pk=request.user.pk)
        else:
            user = User(pk=7) # 비회원 정보
    
        # Result에 모델 저장
        result = Results(img_file_path = '/media/',  first_grade=class_str[sorted_index[4]], 
        first_grade_percentage = int(np.round(100*class_prob[sorted_index[4]])), second_grade = class_str[sorted_index[3]], 
        second_grade_percentage = int(np.round(100*class_prob[sorted_index[3]])), third_grade = class_str[sorted_index[2]], 
        third_grade_percentage = int(np.round(100*class_prob[sorted_index[2]])), user_id = user)
        result.save()
       
        # Result 이미지 경로 수정 
        save_path = os.path.join('/media/', str(result.pk))
        save_path = save_path + '.' + img_field.name.split('.')[-1]
        result.img_file_path=save_path
        result.save()

        # 새로 만든 이미지 이름으로 media 폴더에 이미지 저장

        if not os.path.isdir(settings.MEDIA_ROOT):
            os.makedirs(settings.MEDIA_ROOT)

        save_path = os.path.join(settings.MEDIA_ROOT, str(result.pk))
        save_path = save_path + '.' + img_field.name.split('.')[-1]
        image.save(save_path, format=None)


        # 재학습을 위한 image, text 정보 저장

        center_x = (min_x + max_x)/2
        center_y = (min_y + max_y)/2

        object_width = (max_x - min_x)
        object_height = (max_y - min_y)

        label = sorted_index[4]

        DATASET_SAVE_PATH = 'dataset'
        if not os.path.isdir(DATASET_SAVE_PATH):
            os.makedirs(DATASET_SAVE_PATH)

        text_name = str(result.pk) + ".txt"
        image_name = str(result.pk) + '.' + img_field.name.split('.')[-1]
        img_field.name = image_name

        TEXT_SAVE_PATH = os.path.join(DATASET_SAVE_PATH, text_name)
        IMG_SAVE_PATH = os.path.join(DATASET_SAVE_PATH, image_name)

        with open(TEXT_SAVE_PATH, 'wt') as fw:
            save_str = f"{label} {center_x} {center_y} {object_width} {object_height}" 
            fw.writelines(save_str)
            
        image.save(IMG_SAVE_PATH, format=None)
        
        return redirect(f'/result/show_result/{result.pk}')

def error_page(request):
    return render(request, 'upload/error_page.html')

upload/templates/upload/error_page.html
{% extends 'base.html' %}
{% load static %}

{% block script %}
<link rel="stylesheet" href="{% static 'upload/css/error_page.css' %}">
<link rel="stylesheet" href="{% static 'css/btns.css' %}">
{% endblock script %}

{% block content %}
<div class="error-content">
    <div class="title">
        <p class="oops">
            Oops!
        </p>
        사진의 화질이 좋지 않아 판별할 수 없습니다.<br>
        사진을 다시 선택해주세요.
    </div>

    <div class="btn-box">
        <button type='button' class='btns btn-neg' onclick=location.href="{%url 'home' %}">홈으로 가기</button>
        <button type='button' class='btns btn-pos' onclick=location.href="{%url 'upload:pick_photo' %}">사진 재선택</button>
    </div>
</div>

{% endblock content %}

upload/templates/upload/pick_photo.html
{% extends 'base.html' %}
{% load static %}

{% block script %}
<link rel="stylesheet" href="{% static 'upload/css/img_preview.css'%}">
<link rel="stylesheet" href="{% static 'css/btns.css'%}">
<script src="{% static 'upload/js/img_preview.js' %}"></script>
{% endblock script %}

{% block content %}
<div class="title">
    등급 판정
</div>
<div class="center">
    <form method='post' action='{% url "upload:predict" %}' enctype="multipart/form-data" style="width: 80%;">
        <div class="form-input">
            {% csrf_token %}
            <label for="file-ip-1">upload image</label>
            <input type="file" id="file-ip-1" accept="image/*" onchange="showPreview(event);" name='upimg'>
            <div class="preview">
                <img id="file-ip-1-preview">
            </div>
        </div>
        <div class="predict-box">
            <button type='submit' onClick="return member_submit();" class="predict-btn btn-neg">판별하기</button>
        </div>
        <div id="error-msg" style="visibility: hidden;">
            <p>등급을 판정하고 있습니다.</p>
            <p>잠시만 기다려주세요.</p>
        </div>
    </form>
</div>

<script>
    function member_submit() {
        if (document.getElementById('file-ip-1-preview').style.display != 'block') {
            alert('사진을 선택해주세요!');
                        return false;
        } else if (document.getElementById('file-ip-1-preview').style.display == 'block') {
            document.getElementById('error-msg').style.visibility = "visible";
            document.getElementById('error-msg').className = "alert alert-warning";
        }
    }
</script>

{% endblock content %}