grading/urls.py
from django.conf.urls import url
from django.urls import path

import upload
from upload import views
from . import views

app_name= "grading"

urlpatterns = [
    path('total_distinguish/', views.PostListView.as_view(), name='total_distinguish'),
    path('detail_distinguish/', views.PostListView2.as_view(), name='detail_distinguish'),
    path('show_detail/<int:result_pk>', views.show_detail, name='show_detail'),
]

igs/urls.py
from re import template
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from account.views import UserPasswordResetDoneView, UserPasswordResetView, UserPasswordResetConfirmView

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('account.urls')),
    path('upload/', include('upload.urls')),
    path('grading/', include('grading.urls')),
    path('result/', include('result.urls')),

    path('password_reset/', UserPasswordResetView.as_view(),
        name='password_reset'),

    path('password_reset/done/', UserPasswordResetDoneView.as_view(),
        name='password_reset_done'),

    path('reset/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(
        template_name='password_reset/password_reset_confirm.html'),
        name='password_reset_confirm'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='password_reset/password_reset_complete.html'),
        name='password_reset_complete'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pragmatic/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accountapp.urls')),
]

grading/models.py
from django.db import models

grading/views.py
from typing import Counter
from django.shortcuts import render

from account.models import User
from upload.models import Results
from django.core.paginator import Paginator
from django.views.generic import ListView
from django.contrib.auth import get_user


class PostListView(ListView):
    template_name = "grading/total_distinguish.html"
    model = Results
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = context['paginator']
        page_group_count = 5
        current_page =  int(self.request.GET.get('page', 1))

        start_idx = int((current_page-1)/page_group_count)*page_group_count
        end_idx = start_idx + page_group_count
        page_range = paginator.page_range[start_idx:end_idx]

        start_page = paginator.page(page_range[0])
        end_page = paginator.page(page_range[-1])

        has_previous = start_page.has_previous()
        has_next = end_page.has_next()

        context['page_range'] = page_range
        if has_previous:
            context['has_previous'] = has_previous
            context['previous_page_no'] = start_page.previous_page_number()
        
        if has_next:
            context['has_next'] = has_next
            context['next_page_no'] = end_page.next_page_number()

        return context


class PostListView2(ListView):
    template_name = "grading/detail_distinguish.html"
    paginate_by = 10

    def get_queryset(self):
        return Results.objects.filter(user_id=get_user(self.request).pk).order_by('-register_date')

    def get_context_data(self, **kwargs):
        
        context = super().get_context_data(**kwargs)

        paginator = context['paginator']
        page_group_count = 5
        current_page =  int(self.request.GET.get('page', 1))

        start_idx = int((current_page-1)/page_group_count)*page_group_count
        end_idx = start_idx + page_group_count
        page_range = paginator.page_range[start_idx:end_idx]

        start_page = paginator.page(page_range[0])
        end_page = paginator.page(page_range[-1])

        has_previous = start_page.has_previous()
        has_next = end_page.has_next()

        context['page_range'] = page_range
        if has_previous:
            context['has_previous'] = has_previous
            context['previous_page_no'] = start_page.previous_page_number()
        
        if has_next:
            context['has_next'] = has_next
            context['next_page_no'] = end_page.next_page_number()

        return context

def show_detail(request, result_pk):
    data = Results.objects.get(pk=result_pk)

    return render(request, 'grading/show_detail.html', {'result' : data})

grading/templates/grading/detail_distinguish.html
{% extends 'base.html' %}
{% load static %}
{% load pybo_filter %}

{% block script %}
<link rel="stylesheet" href="{% static 'grading/css/distinguish.css'%}">
<link rel="stylesheet" href="{% static 'css/btns.css'%}">
{% if not user.is_authenticated %}
<meta http-equiv="refresh" content="3;url={% url 'grading:total_distinguish'%}" />
{% endif %}
{% endblock script %}

{% block content %}
<div id="detail-box">
    <div class="title">
        <p class="font-weight-bold" style="display: inline-block; margin: 0;">{{user.username}}</p> 님의 이력 조회
    </div>
    <div class="buttons">
        <a href="{% url 'grading:total_distinguish'%}" type="button" class="btn btn-sm btn-neg">전체
            이력</a>

        <a href="{% url 'grading:detail_distinguish'%}" class="btn btn-sm btn-pos">나의 이력</a>
    </div>
</div>

<div id="table-box">
    <table class="table table-striped table-sm">
        <thead class="thead-dark">
            <tr>
                <th scope="col">No</th>
                <th scope="col">날짜</th>
                <th scope="col">등급</th>
            </tr>
        </thead>
        <tbody>
            {% for b in object_list %}
            <tr onClick=location.href="{%url 'grading:show_detail' b.pk %}" style="cursor:pointer;">
                <td>{{page_obj.number|sub:1|multi:10|add:forloop.counter}}</td>
                <td>{{b.register_date}}</td>
                {% if b.modified_grade != None %}
                <td>{{b.modified_grade}}</td>
                {% else %}
                <td>{{b.first_grade}}</td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% if is_paginated %}
    <ul class='pagination justify-content-center'>
        <!-- 이전페이지그룹으로 이동하는 링크 -->
        {% if has_previous %}
        <li class='page-item'>
            <a href="{% url 'grading:total_distinguish' %}?page={{previous_page_no}}" class='page-link'>이전</a>
        </li>
        {% else %}
        <li class='page-item' style="color: #969696">
            <span class='page-link'>이전</span>
        </li>
        {% endif %}

        <!-- 페이지번호 링크.  page_obj.number:현재페이지의 번호-->
        {% for page in page_range %}
        {% if page == page_obj.number %}
        <li class='page-item active'>
            <span class='page-link' style="background-color: #969696; color: #FFFFFF; border: #969696;">{{page}}</span>
        </li>
        {% else %}
        <li class='page-item'>
            <a href="{% url 'grading:total_distinguish' %}?page={{page}}" class='page-link'>{{page}}</a>
        </li>
        {% endif %}
        {% endfor %}


        <!-- 다음페이지그룹으로 이동하는 링크 -->
        {% if has_next %}
        <li class='page-item'>
            <a href="{% url 'grading:total_distinguish' %}?page={{next_page_no}}" class='page-link'>다음</a>
        </li>
        {% else %}
        <li class='page-item'>
            <span class='page-link' style="color: #969696">다음</span>
        </li>
        {% endif %}
    </ul>

    {% endif %}
</div>

{% endblock content %}

grading/templates/grading/show_detail.html
{% extends 'base.html' %}
{% load static %}

{% block script %}
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2.0.0"></script>
<link rel='stylesheet' href="{% static 'grading/css/show_detail.css' %}">
<link rel='stylesheet' href="{% static 'css/btns.css' %}">
{% endblock script %}

{% block content %}
<div class="title">
  상세 이력
</div>

<div class="detail-content">
  <div class="img-box">
    <img class="mx-auto d-block predict-img" src="{{ result.img_file_path }}">
  </div> <!-- 이미지-->

  <div>
    <input id="f_g" type="hidden" value={{result.first_grade}}>
    <input id="s_g" type="hidden" value={{result.second_grade}}>
    <input id="t_g" type="hidden" value={{result.third_grade}}>
    <input id="f_g_p" type="hidden" value={{result.first_grade_percentage}}>
    <input id="s_g_p" type="hidden" value={{result.second_grade_percentage}}>
    <input id="t_g_p" type="hidden" value={{result.third_grade_percentage}}>
  </div>

  {% if result.modified_grade == None %}
  <div class="chart-box">
    <canvas id="myChart" style="height: 85%; width: 70%;"></canvas>
  </div> <!-- chart.js -->
  {% endif %}

  {% if result.modified_grade != None %}
  <div style="margin: 5vh 0;">
  {% endif %}
    <div style="height: 15%;">
      {% if result.modified_grade != None %}
      <div class="text">
        판별 결과 <span style="color:red;">{{result.modified_grade}} 등급 </span>입니다.
      </div>
      {% else %}
      <div class="text">
        판별 결과 <span style="color:red;">{{result.first_grade}} 등급 </span>입니다.
      </div>
      {% endif %}
      

      <form method="post" style="text-align: center;">
        {% csrf_token %}

        <button type="button" class="btn-back btn-neg" onclick="history.back()">뒤로가기</button>
      </form>
    </div>
  {% if result.modified_grade != None %}
  </div>
  {% endif %}

</div>

<script>

  var f_g = document.getElementById("f_g").value;
  var s_g = document.getElementById('s_g').value;
  var t_g = document.getElementById('t_g').value;

  var f_g_p = document.getElementById("f_g_p").value;
  var s_g_p = document.getElementById('s_g_p').value;
  var t_g_p = document.getElementById('t_g_p').value;

  var ctx = document.getElementById('myChart');
  var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
      labels: [f_g + ' 등급', s_g + ' 등급', t_g + ' 등급'],
      datasets: [{
        label: '# of Percentage',
        data: [f_g_p, s_g_p, t_g_p],
        backgroundColor: [
          'rgba(255, 206, 86, 0.2)',
          'rgba(255, 159, 64, 0.2)',
          'rgba(255, 99, 132, 0.2)',
        ],
        borderColor: [
          'rgba(255, 206, 86, 1)',
          'rgba(255, 159, 64, 1)',
          'rgba(255, 99, 132, 1)',
        ],
        borderWidth: 1
      }]
    },
    options: {
      // 퍼센트 보이도록 설정
      animation: {
        duration: 500,
        easing: "easeOutQuart",
        onComplete: function () {
          var ctx = this.chart.ctx;
          ctx.font = Chart.helpers.fontString(Chart.defaults.global.defaultFontFamily, 'normal', Chart.defaults.global.defaultFontFamily);
          ctx.textAlign = 'center';
          ctx.textBaseline = 'bottom';

          this.data.datasets.forEach(function (dataset) {
            for (var i = 0; i < dataset.data.length; i++) {
              var model = dataset._meta[Object.keys(dataset._meta)[0]].data[i]._model,
                scale_max = dataset._meta[Object.keys(dataset._meta)[0]].data[i]._yScale.maxHeight;
              ctx.fillStyle = '#444';
              var y_pos = model.y + 5;
              // Make sure data value does not get overflown and hidden
              // when the bar's value is too close to max value of scale
              // Note: The y value is reverse, it counts from top down
              if ((scale_max - model.y) / scale_max >= 0.93)
                y_pos = model.y + 20;
              ctx.fillText(dataset.data[i] + '%', model.x, y_pos);
            }
          });
        }
      },
      // css 설정을 위한 설정
      responsive: false,
      // legend를 지우는 설정
      legend: {
        display: false,
      },
      scales: {
        xAxes: [{
          gridLines: { //x축 gridLines 지우는 옵션 
            display: false,
            drawBorder: false,
          },
        }],

        yAxes: [{
          gridLines: { //y축 선 지우기
            drawBorder: false,
            display: false
          },
          ticks: {
            beginAtZero: true
          }
        }]
      }
    }
  });
</script>
{% endblock content %} -->

grading/templates/grading/total_distinguish.html
{% extends 'base.html' %}
{% load static %}
{% load pybo_filter %}

{% block script %}
<link rel="stylesheet" href="{% static 'grading/css/distinguish.css'%}">
<link rel="stylesheet" href="{% static 'css/btns.css'%}">
{% endblock script %}

{% block content %}
<div id="detail-box">
  <div class="title">
    전체 이력 조회
  </div>

  <div class="buttons">
    <a href="{% url 'grading:total_distinguish' %}" type="button" class="btn btn-sm btn-pos">전체
      이력</a>
    {% if user.is_authenticated %}
    <a href="{% url 'grading:detail_distinguish' %}" type="button" class="btn btn-sm btn-neg">나의
      이력</a>
    {% endif %}
    {% if not user.is_authenticated %}
    <a href="#" onclick="notUser()" type="button" class="btn btn-sm btn-neg">나의 이력</a>
    {% endif %}
    <script>
      function notUser() {
        alert("로그인을 해주세요!")
      }
    </script>
  </div>
</div>

<div id="table-box">
  <table class="table table-striped table-sm">
    <thead class="thead-dark">
      <tr>
        <th scope="col">No</th>
        <th scope="col">날짜</th>
        <th scope="col">등급</th>
        <th scope="col">닉네임</th>
      </tr>
    </thead>
    <tbody>
      {% for a in object_list %}
      <tr onClick=location.href="{%url 'grading:show_detail' a.pk %}" style="cursor:pointer;">
        <td>{{page_obj.number|sub:1|multi:10|add:forloop.counter}}</td>
        <td>{{a.register_date}}</td>
        {% if a.modified_grade != None %}
        <td>{{a.modified_grade}}</td>
        {% else %}
        <td>{{a.first_grade}}</td>
        {% endif %}
        <td>{{a.user_id.username}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  {% if is_paginated %}
  <ul class='pagination justify-content-center'>
    <!-- 이전페이지그룹으로 이동하는 링크 -->
    {% if has_previous %}
    <li class='page-item'>
      <a href="{% url 'grading:total_distinguish' %}?page={{previous_page_no}}" class='page-link'>이전</a>
    </li>
    {% else %}
    <li class='page-item'>
      <span class='page-link' style="color: #969696">이전</span>
    </li>
    {% endif %}

    <!-- 페이지번호 링크.  page_obj.number:현재페이지의 번호-->
    {% for page in page_range %}
    {% if page == page_obj.number %}
    <li class='page-item active'>
      <span class='page-link' style="background-color: #969696; color: #FFFFFF; border: #969696;">{{page}}</span>
    </li>
    {% else %}
    <li class='page-item'>
      <a href="{% url 'grading:total_distinguish' %}?page={{page}}" class='page-link' style="color: #969696">{{page}}</a>
    </li>
    {% endif %}
    {% endfor %}


    <!-- 다음페이지그룹으로 이동하는 링크 -->
    {% if has_next %}
    <li class='page-item'>
      <a href="{% url 'grading:total_distinguish' %}?page={{next_page_no}}" class='page-link'>다음</a>
    </li>
    {% else %}
    <li class='page-item'>
      <span class='page-link' style="color: #969696">다음</span>
    </li>
    {% endif %}
  </ul>
</div>

{% endif %}


{% endblock content %}