account/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from account.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "account"

urlpatterns = [
    path('login/', LoginView.as_view(template_name='account/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

grading/urls.py
from django.conf.urls import url
from django.urls import path

import upload
from upload import views
from . import views

app_name= "grading"

urlpatterns = [
    path('total_distinguish/', views.PostListView.as_view(), name='total_distinguish'),
    path('detail_distinguish/', views.PostListView2.as_view(), name='detail_distinguish'),
    path('show_detail/<int:result_pk>', views.show_detail, name='show_detail'),
]

igs/urls.py
from re import template
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from account.views import UserPasswordResetDoneView, UserPasswordResetView, UserPasswordResetConfirmView

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('account.urls')),
    path('upload/', include('upload.urls')),
    path('grading/', include('grading.urls')),
    path('result/', include('result.urls')),

    path('password_reset/', UserPasswordResetView.as_view(),
        name='password_reset'),

    path('password_reset/done/', UserPasswordResetDoneView.as_view(),
        name='password_reset_done'),

    path('reset/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(
        template_name='password_reset/password_reset_confirm.html'),
        name='password_reset_confirm'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='password_reset/password_reset_complete.html'),
        name='password_reset_complete'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pragmatic/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accountapp.urls')),
]

upload/urls.py
from django.urls import path
# from upload.views import PickPhotoView
from . import views
from django.views.generic import TemplateView

app_name = "upload"

urlpatterns = [
    path('pick_photo', TemplateView.as_view(template_name='upload/pick_photo.html'), name='pick_photo'),
    path('predict', views.predict, name='predict'),
    path('error_page', views.error_page, name="error_page")
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'img/iguessso_cow.png' %}">


    <!-- bootstrap4 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"
        integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF"
        crossorigin="anonymous"></script>

    <!-- import base js, css -->
    <link rel='stylesheet' href="{% static 'css/menu.css' %}">
    <link rel='stylesheet' href="{% static 'css/btns.css' %}">
    <script src="{% static 'js/menu.js' %}"></script>

    <!-- import css/js -->
    {% block script %}{% endblock script %}

    <title>알겠소</title>
</head>

<body class="cotianer vh-100 w-100">
    <div class="row p-0 justify-content-md-center m-0">
        <div class="col-md-5 col-12 p-0 vh-100 w-100">

            <div class="main-header">
                <span id='menu-btn' style="font-size:30px;cursor:pointer">&#9776;</span>
                <a class="main-logo" href="{% url 'home' %}">
                    <img src="{% static 'img/iguessso_font.png' %}" class="logo-img" alt="알겠소">
                </a>
            </div>

            <div id="mySidenav" class="sidenav shadow-lg">
                <a href="javascript:void(0)" class="closebtn">&times;</a>
                <div class="login-info">
                    {% if user.is_authenticated %}
                    {{user.username}} 님 안녕하세요.
                    {% endif %}

                    {% if not user.is_authenticated %}
                    로그인이 필요합니다.
                    {% endif %}
                </div>
                <a href="{% url 'upload:pick_photo' %}">등급 판정</a>
                <a href="{% url 'grading:total_distinguish' %}">이력 조회</a>

                {% if not user.is_authenticated %}
                <a href="{% url 'account:create' %}">회원가입</a>
                <a href="{% url 'account:login' %}">로그인</a>

                {% elif user.is_authenticated %}
                <a href="{% url 'account:detail' user.id %}">마이 페이지</a>
                <div class="logout-content">
                    <button class="btn btn-neg logout-btn">
                        <a href="{% url 'account:logout' %}?next={{ request.path }}">로그아웃</a>
                    </button>
                </div>
                {% endif %}
            </div>
            <div class="content-body">
                {% block content %}
                {% endblock content %}
            </div>
        </div>
    </div>
</body>

</html>

templates/footer_.html
<!-- 사이드 메뉴에만 추가하도록 추후 수정 -->
<div class="igs_footer">
    <div class="igs_footer_button">
        <span>공지사항</span>
        <span>제휴문의</span>
        <span>서비스 소개</span>
    </div>
    <div style="margin-top: 1rem;">
        <h6 class="igs_logo">Team Alphaca</h6>
    </div>

</div>

templates/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'img/iguessso_cow.png' %}">

    <!-- bootstrap4 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"
        integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF"
        crossorigin="anonymous"></script>

    <!-- import js, css -->
    <script src="{% static 'js/menu.js' %}"></script>
    <link rel='stylesheet' href="{% static 'css/home.css' %}">
    <link rel='stylesheet' href="{% static 'css/btns.css' %}">

    <title>알겠소</title>
</head>


<body class="cotianer">
    <div class="row p-0 justify-content-md-center m-0">
        <div class="col-md-5 col-12 p-0 vh-100 vw-100">
            <div class="row h-100 w-100 m-0">
                <div id="mySidenav" class="sidenav shadow-lg">
                    <a href="javascript:void(0)" class="closebtn">&times;</a>
                    <div class="login-info">
                        {% if user.is_authenticated %}
                        {{user.username}} 님 안녕하세요.
                        {% endif %}

                        {% if not user.is_authenticated %}
                        로그인이 필요합니다.
                        {% endif %}
                    </div>
                    <a href="{% url 'upload:pick_photo' %}">등급 판정</a>
                    <a href="{% url 'grading:total_distinguish' %}">이력 조회</a>

                    {% if not user.is_authenticated %}
                    <a href="{% url 'account:create' %}">회원가입</a>
                    <a href="{% url 'account:login' %}">로그인</a>

                    {% elif user.is_authenticated %}
                    <a href="{% url 'account:detail' user.id %}">마이 페이지</a>
                    <div class="logout-content">
                        <button class="btn btn-neg logout-btn">
                            <a href="{% url 'account:logout' %}?next={{ request.path }}">로그아웃</a>
                        </button>
                    </div>
                    {% endif %}
                </div>
                <div class="col-12 p-0" style="height: 70%;">
                    <div class="main-header">
                        <span id="menu-btn" style="font-size:30px;cursor:pointer">&#9776;</span>
                    </div>
                    <div class="main-logo">
                        <img src="{% static 'img/[PNG]iguessso_logo.png' %}" class="img-fluid" alt="알겠소">
                    </div>
                </div>
                <div class="col-12 menu-list">
                    <div class="row h-100">
                        <div class="menu-box col-6 border-right border-bottom border-dark text-center">
                            <a href="{% url 'upload:pick_photo' %}" class="menu-icon p-0">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                    class="bi bi-search" viewBox="0 0 16 16">
                                    <path
                                        d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
                                </svg>
                                등급 판정
                            </a>
                        </div>


                        <div class="menu-box col-6 border-bottom border-dark text-center">
                            <a href="{% url 'grading:total_distinguish' %}" class="menu-icon p-0">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                    class="bi bi-list-ul" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd"
                                        d="M5 11.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zm-3 1a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm0 4a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm0 4a1 1 0 1 0 0-2 1 1 0 0 0 0 2z" />
                                </svg>
                                이력 조회
                            </a>
                        </div>

                        {% if user.is_authenticated %}
                        <div class="menu-box col-6 border-right border-dark text-center">
                            <a href="{% url 'account:detail' user.id %}" class="menu-icon p-0">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                    class="bi bi-person-circle" viewBox="0 0 16 16">
                                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
                                    <path fill-rule="evenodd"
                                        d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z" />
                                </svg>
                                마이 페이지
                            </a>
                        </div>

                        <div class="menu-box col-6 text-center">
                            <a href="{% url 'account:logout' %}" class="menu-icon p-0">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                    class="bi bi-door-open" viewBox="0 0 16 16">
                                    <path d="M8.5 10c-.276 0-.5-.448-.5-1s.224-1 .5-1 .5.448.5 1-.224 1-.5 1z" />
                                    <path
                                        d="M10.828.122A.5.5 0 0 1 11 .5V1h.5A1.5 1.5 0 0 1 13 2.5V15h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V1.5a.5.5 0 0 1 .43-.495l7-1a.5.5 0 0 1 .398.117zM11.5 2H11v13h1V2.5a.5.5 0 0 0-.5-.5zM4 1.934V15h6V1.077l-6 .857z" />
                                </svg>
                                로그아웃
                            </a>
                        </div>

                        {% elif not user.is_authenticated %}
                        <div class="menu-box col-6 border-right border-dark text-center">
                            <a href="{% url 'account:create' %}" class="menu-icon p-0">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                    class="bi bi-person-plus-fill" viewBox="0 0 16 16">
                                    <path
                                        d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
                                    <path fill-rule="evenodd"
                                        d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z" />
                                </svg>
                                회원가입
                            </a>
                        </div>

                        <div class="menu-box col-6 text-center">
                            <a href="{% url 'account:login' %}" class="menu-icon p-0">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                    class="bi bi-door-closed" viewBox="0 0 16 16">
                                    <path
                                        d="M3 2a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v13h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V2zm1 13h8V2H4v13z" />
                                    <path d="M9 9a1 1 0 1 0 2 0 1 1 0 0 0-2 0z" />
                                </svg>
                                로그인
                            </a>
                        </div>
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>